#!/usr/bin/python3

import subprocess
import os
import shutil
import sys

clean_project = False
run_executable = False

# check if we need to clean the project or run after building
for arg in sys.argv:
  if arg == "--clean":
    clean_project = True
  elif arg == "--run":
    run_executable = True

# removing the old bin folder
if os.path.isdir("bin"):
  shutil.rmtree("bin")

if clean_project:
  if os.path.isdir("build"):
    shutil.rmtree("build")

  if os.path.exists(".cache"):
    shutil.rmtree(".cache")

if os.path.exists("ml"):
  os.remove("ml")

# installing dependencies using conan
subprocess.run([
  "conan", 
  "install", 
  ".",
  "--output-folder=build", 
  "--build=missing"#,
])

# generating the cmake files
os.chdir("build")
subprocess.run([
  "cmake", 
  "..", 
  "-DCMAKE_TOOLCHAIN_FILE='conan_toolchain.cmake'", 
  "-DCMAKE_BUILD_TYPE=Debug",
  "-DCMAKE_EXPORT_COMPILE_COMMANDS=1"
])

# building the project using the generated cmake files
subprocess.run(["cmake", "--build", ".", "--config Debug"])

# move the bin folder to the root dir and run if needed
if os.path.exists("bin"):
  shutil.move("bin", "../bin")

  if run_executable:
    subprocess.run(["../bin/ml"])
