#!/usr/bin/python3

from jinja2 import Environment, FileSystemLoader
import os
import json

root_path = os.path.dirname(os.path.abspath(__file__))
env_path = f"{root_path}/../templates"

atlas_name = "main"

with open(f"{root_path}/../res/images/main.json") as file:
  data = json.load(file)
  atlas_w = data["meta"]["size"]["w"]
  atlas_h = data["meta"]["size"]["h"]
  atlas = {}
  atlas["name"] = atlas_name
  sprites = []
  for sprite_data in data["frames"]:
    frame = sprite_data["frame"]
    sprite = {
      "name": sprite_data["filename"][:-4],
      "atlas": atlas_name,
      "tlx": frame["x"] / atlas_w,
      "tly": frame["y"] / atlas_h,
      "trx" : (frame["x"] + frame["w"]) / atlas_w,
      "try" : frame["y"] / atlas_h,
      "blx" : frame["x"] / atlas_w,
      "bly" : (frame["y"] + frame["h"]) / atlas_h,
      "brx" : (frame["x"] + frame["w"]) / atlas_w,
      "bry" : (frame["y"] + frame["h"]) / atlas_h
    }
    sprites.append(sprite)

  atlas["sprites"] = sprites

  environment = Environment(loader=FileSystemLoader(env_path))
  template = environment.get_template("sprite_atlas_template.jinga")

  path = f"{root_path}/../src/sprite/_gen_MainAtlas.hpp"
  with open(path, mode="w", encoding="utf-8") as file:
    file.write(template.render(atlas))

